### ISSUE TITLE
Blank Screen

### ISSUE THREAD

**Issue by asadarko** [mapswipe/mapswipe-web#15] opened 2024-05-21 13:55 UTC
**Describe the bug**
When I go to web.mapswipe.org and try to open the page, I only see a white screen and nothing loads.
**To Reproduce**
Go to [web.mapswipe.org](https://web.mapswipe.org/).
Attempt to open the main page.
Select a project. 
Go through the instructions and accept.
Observe the screen.

**Expected behavior**
The main page should load properly, displaying the MapSwipe interface and content.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [. iOS]
 - Browser [safari]

Uploading screen-recording-2024-05-20-at-100401-am_KAkc8vwA.mp4…

**Additional context**

**Comment by xplora1a** [comment] 2024-05-21 19:20
I am getting the same. 
OS Ubuntu
browser Chrome Version 125.0.6422.60 (Official Build) (64-bit)

![image](https://github.com/mapswipe/mapswipe-web/assets/1844128/c69af378-1e30-4569-9ad8-25b8c9dabe3a)

then the screen blanks and the v-container object is empty

![image](https://github.com/mapswipe/mapswipe-web/assets/1844128/a18164c0-ef33-4b6d-8f99-d9bc52be608f)

**Comment by ofr1tz** [comment] 2024-05-22 12:09
Thanks for sharing the issue and the information included.

I'm closing this here as it is a duplicate of #14 

Will look into it.

**Closed by ofr1tz** 2024-05-22 12:09 UTC
